FROM ubuntu:16.04

WORKDIR /root
RUN apt update && apt-get install -y wget
RUN wget https://gethstore.blob.core.windows.net/builds/geth-linux-amd64-1.8.10-eae63c51.tar.gz
COPY checksum.md5 checksum.md5
RUN md5sum -c checksum.md5
RUN tar -zvxf geth-linux-amd64-1.8.10-eae63c51.tar.gz && mv geth-linux-amd64-1.8.10-eae63c51 go-ethereum
RUN cp go-ethereum/* /usr/local/bin

ENTRYPOINT ["geth"]